//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class NepotvrdjeniUcenici
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public double Visina { get; set; }
        public string Sifra { get; set; }
        public int Godine { get; set; }
        public string Naziv_Skole { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string pol { get; set; }
        public string JMBG { get; set; }
        public Nullable<int> Razred { get; set; }
    
        public virtual Skola Skola { get; set; }
    }
}
