//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkruzniMec
    {
        public int Id { get; set; }
        public Nullable<int> Razred1 { get; set; }
        public Nullable<int> Razred2 { get; set; }
        public Nullable<int> Poen1 { get; set; }
        public Nullable<int> Poen2 { get; set; }
        public string Odigrano { get; set; }
        public string NazivSkole1 { get; set; }
        public string NazivSkole2 { get; set; }
    }
}
