//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pobede
    {
        public int Id { get; set; }
        public Nullable<int> Id_tima { get; set; }
        public string NazivSkole { get; set; }
    
        public virtual Tim Tim { get; set; }
    }
}
