//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class RsSkolskog
    {
        public int Id { get; set; }
        public Nullable<int> id_ucenika { get; set; }
        public string NazivSkole { get; set; }
        public Nullable<int> Razred { get; set; }
        public Nullable<int> Red { get; set; }
        public Nullable<int> Kolona { get; set; }
    }
}
